apiVersion: batch/v1
kind: Job
metadata:
  name: zitadel-bootstrapper
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: zitadel-bootstrapper
        image: gothenburg/zitadel-bootstrapper:latest
        env:
          - name: zitadelOrgName
            value: {{ index .Values "zitadel-bootstrapper" "OrgName" }}
          - name: zitadelServiceUser
            value: {{ index .Values "zitadel-bootstrapper" "ServiceUserName" }}
          - name: zitadelServiceUserToken
            valueFrom:
              secretKeyRef:
                name: {{ index .Values "zitadel-bootstrapper" "ServiceUserName" }}
      restartPolicy: OnFailure
