apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-secrets
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: zitadel-bootstrapper
    apiGroup: ""
roleRef:
  kind: Role
  name: secrets-creator
  apiGroup: ""
